export const statusEffects = [
    {
        id: 'accelerated',
        name: 'FU.Accelerated',
        icon: 'systems/projectfu/styles/static/statuses/Accelerated.webp',
    },
    {
        id: 'aura',
        name: 'FU.Aura',
        icon: 'systems/projectfu/styles/static/statuses/Aura.webp',
    },
    {
        id: 'barrier',
        name: 'FU.Barrier',
        icon: 'systems/projectfu/styles/static/statuses/Barrier.webp',
    },
    {
        id: 'beserk',
        name: 'FU.Beserk',
        icon: 'systems/projectfu/styles/static/statuses/Beserk.webp',
    },
    {
        id: 'blinded',
        name: 'FU.Blinded',
        icon: 'systems/projectfu/styles/static/statuses/Blinded.webp',
    },
    {
        id: 'death',
        name: 'FU.Death',
        icon: 'systems/projectfu/styles/static/statuses/Death.webp',
    },
    {
        id: 'dazed',
        name: 'FU.Dazed',
        icon: 'systems/projectfu/styles/static/statuses/Dazed.webp',
        stats: ['ins'],
        mod: -2,
    },
    {
        id: 'dex-down',
        name: 'FU.DEXDown',
        icon: 'systems/projectfu/styles/static/statuses/DexDown.webp',
        stats: ['dex'],
        mod: -2,
    },
    {
        id: 'dex-up',
        name: 'FU.DEXUp',
        icon: 'systems/projectfu/styles/static/statuses/DexUp.webp',
        stats: ['dex'],
        mod: 2,
    },
    {
        id: 'enraged',
        name: 'FU.Enraged',
        icon: 'systems/projectfu/styles/static/statuses/Enraged.webp',
        stats: ['dex', 'ins'],
        mod: -2,
    },
    {
        id: 'guard',
        name: 'FU.Guard',
        icon: 'systems/projectfu/styles/static/icons/fu-guard.svg',
    },    
    {
        id: 'ins-down',
        name: 'FU.INSDown',
        icon: 'systems/projectfu/styles/static/statuses/InsDown.webp',
        stats: ['ins'],
        mod: -2,
    },
    {
        id: 'ins-up',
        name: 'FU.INSUp',
        icon: 'systems/projectfu/styles/static/statuses/InsUp.webp',
        stats: ['ins'],
        mod: 2,
    },
    {
        id: 'ko',
        name: 'FU.KO',
        icon: 'systems/projectfu/styles/static/statuses/KO.webp',
    },
    {
        id: 'mig-down',
        name: 'FU.MIGDown',
        icon: 'systems/projectfu/styles/static/statuses/MigDown.webp',
        stats: ['mig'],
        mod: -2,
    },
    {
        id: 'mig-up',
        name: 'FU.MIGUp',
        icon: 'systems/projectfu/styles/static/statuses/MigUp.webp',
        stats: ['mig'],
        mod: 2,
    },
    {
        id: 'reflect',
        name: 'FU.Reflect',
        icon: 'systems/projectfu/styles/static/statuses/Reflect.webp',
    },
    {
        id: 'regen',
        name: 'FU.Regen',
        icon: 'systems/projectfu/styles/static/statuses/Regen.webp',
    },
    {
        id: 'shaken',
        name: 'FU.Shaken',
        icon: 'systems/projectfu/styles/static/statuses/Shaken.webp',
        stats: ['wlp'],
        mod: -2,
    },
    {
        id: 'sleep',
        name: 'FU.Sleep',
        icon: 'systems/projectfu/styles/static/statuses/Sleep.webp',
    },
    {
        id: 'slow',
        name: 'FU.Slow',
        icon: 'systems/projectfu/styles/static/statuses/Slow.webp',
        stats: ['dex'],
        mod: -2,
    },
    {
        id: 'poisoned',
        name: 'FU.Poisoned',
        icon: 'systems/projectfu/styles/static/statuses/Poisoned.webp',
        stats: ['mig', 'wlp'],
        mod: -2,
    },
    {
        id: 'weak',
        name: 'FU.Weak',
        icon: 'systems/projectfu/styles/static/statuses/Weak.webp',
        stats: ['mig'],
        mod: -2,
    },
    {
        id: 'wlp-down',
        name: 'FU.WLPDown',
        icon: 'systems/projectfu/styles/static/statuses/WlpDown.webp',
        stats: ['wlp'],
        mod: -2,
    },
    {
        id: 'wlp-up',
        name: 'FU.WLPUp',
        icon: 'systems/projectfu/styles/static/statuses/WlpUp.webp',
        stats: ['wlp'],
        mod: 2,
    },
    {
        id: 'crisis',
        name: 'FU.Crisis',
        icon: 'systems/projectfu/styles/static/statuses/Status_Bleeding.png',
    },
];
