export const statusEffects = [
	{
		id: 'accelerated',
		name: 'FU.Accelerated',
		icon: 'systems/projectfu/styles/static/statuses/Accelerated.webp',
		statuses: ['accelerated'],
	},
	{
		id: 'aura',
		name: 'FU.Aura',
		icon: 'systems/projectfu/styles/static/statuses/Aura.webp',
		statuses: ['aura'],
	},
	{
		id: 'barrier',
		name: 'FU.Barrier',
		icon: 'systems/projectfu/styles/static/statuses/Barrier.webp',
		statuses: ['barrier'],
	},
	{
		id: 'beserk',
		name: 'FU.Beserk',
		icon: 'systems/projectfu/styles/static/statuses/Beserk.webp',
		statuses: ['berserk'],
	},
	{
		id: 'dazed',
		name: 'FU.Dazed',
		icon: 'systems/projectfu/styles/static/statuses/Dazed.webp',
		stats: ['ins'],
		mod: -2,
		statuses: ['dazed'],
	},
	{
		id: 'dex-down',
		name: 'FU.DEXDown',
		icon: 'systems/projectfu/styles/static/statuses/DexDown.webp',
		stats: ['dex'],
		mod: -2,
		statuses: ['dex-down'],
	},
	{
		id: 'dex-up',
		name: 'FU.DEXUp',
		icon: 'systems/projectfu/styles/static/statuses/DexUp.webp',
		stats: ['dex'],
		mod: 2,
		statuses: ['dex-up'],
	},
	{
		id: 'enraged',
		name: 'FU.Enraged',
		icon: 'systems/projectfu/styles/static/statuses/Enraged.webp',
		stats: ['dex', 'ins'],
		mod: -2,
		statuses: ['enraged'],
	},
	{
		id: 'flying',
		name: 'FU.Flying',
		icon: 'systems/projectfu/styles/static/statuses/Flying.webp',
		statuses: ['flying'],
	},
	{
		id: 'guard',
		name: 'FU.Guard',
		icon: 'systems/projectfu/styles/static/statuses/Guard.webp',
		statuses: ['guard'],
	},
	{
		id: 'ins-down',
		name: 'FU.INSDown',
		icon: 'systems/projectfu/styles/static/statuses/InsDown.webp',
		stats: ['ins'],
		mod: -2,
		statuses: ['ins-down'],
	},
	{
		id: 'ins-up',
		name: 'FU.INSUp',
		icon: 'systems/projectfu/styles/static/statuses/InsUp.webp',
		stats: ['ins'],
		mod: 2,
		statuses: ['ins-up'],
	},
	{
		id: 'ko',
		name: 'FU.KO',
		icon: 'systems/projectfu/styles/static/statuses/KO.webp',
		statuses: ['ko'],
	},
	{
		id: 'mig-down',
		name: 'FU.MIGDown',
		icon: 'systems/projectfu/styles/static/statuses/MigDown.webp',
		stats: ['mig'],
		mod: -2,
		statuses: ['mig-down'],
	},
	{
		id: 'mig-up',
		name: 'FU.MIGUp',
		icon: 'systems/projectfu/styles/static/statuses/MigUp.webp',
		stats: ['mig'],
		mod: 2,
		statuses: ['mig-up'],
	},
	{
		id: 'reflect',
		name: 'FU.Reflect',
		icon: 'systems/projectfu/styles/static/statuses/Reflect.webp',
		statuses: ['reflect'],
	},
	{
		id: 'regen',
		name: 'FU.Regen',
		icon: 'systems/projectfu/styles/static/statuses/Regen.webp',
		statuses: ['regen'],
	},
	{
		id: 'shaken',
		name: 'FU.Shaken',
		icon: 'systems/projectfu/styles/static/statuses/Shaken.webp',
		stats: ['wlp'],
		mod: -2,
		statuses: ['shaken'],
	},
	{
		id: 'sleep',
		name: 'FU.Sleep',
		icon: 'systems/projectfu/styles/static/statuses/Sleep.webp',
		statuses: ['sleep'],
	},
	{
		id: 'slow',
		name: 'FU.Slow',
		icon: 'systems/projectfu/styles/static/statuses/Slow.webp',
		stats: ['dex'],
		mod: -2,
		statuses: ['slow'],
	},
	{
		id: 'poisoned',
		name: 'FU.Poisoned',
		icon: 'systems/projectfu/styles/static/statuses/Poisoned.webp',
		stats: ['mig', 'wlp'],
		mod: -2,
		statuses: ['poisoned'],
	},
	{
		id: 'weak',
		name: 'FU.Weak',
		icon: 'systems/projectfu/styles/static/statuses/Weak.webp',
		stats: ['mig'],
		mod: -2,
		statuses: ['weak'],
	},
	{
		id: 'wlp-down',
		name: 'FU.WLPDown',
		icon: 'systems/projectfu/styles/static/statuses/WlpDown.webp',
		stats: ['wlp'],
		mod: -2,
		statuses: ['wlp-down'],
	},
	{
		id: 'wlp-up',
		name: 'FU.WLPUp',
		icon: 'systems/projectfu/styles/static/statuses/WlpUp.webp',
		stats: ['wlp'],
		mod: 2,
		statuses: ['wlp-up'],
	},
	{
		id: 'crisis',
		name: 'FU.Crisis',
		icon: 'systems/projectfu/styles/static/statuses/Crisis.webp',
		statuses: ['crisis'],
	},
];
